/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoadingScreen;

import Login.login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingtxt = new javax.swing.JLabel();
        persentxt = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        loadingtxt.setBackground(new java.awt.Color(29, 46, 66));
        loadingtxt.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        loadingtxt.setForeground(new java.awt.Color(29, 46, 66));
        loadingtxt.setText("Loading...");
        getContentPane().add(loadingtxt);
        loadingtxt.setBounds(10, 630, 520, 50);

        persentxt.setBackground(new java.awt.Color(29, 46, 66));
        persentxt.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        persentxt.setForeground(new java.awt.Color(29, 46, 66));
        persentxt.setText("0 %");
        getContentPane().add(persentxt);
        persentxt.setBounds(1090, 640, 100, 40);

        loadingBar.setBackground(new java.awt.Color(255, 255, 255));
        loadingBar.setForeground(new java.awt.Color(84, 173, 186));
        getContentPane().add(loadingBar);
        loadingBar.setBounds(0, 680, 1150, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoadingScreen/Loading Screen2.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1152, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LoadingScreen ls = new LoadingScreen();
        ls.setVisible(true);
        login lgn = new login();
        try {
            
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                ls.persentxt.setText(i + "%");
                
                if (i==0) {
                    ls.loadingtxt.setText("Memulai Aplikasi...");
                }
                if (i==20) {
                    ls.loadingtxt.setText("Memuat Aplikasi...");
                }
                if (i==45) {
                    ls.loadingtxt.setText("Menyambungkan Database...");
                }
                if (i==65) {
                    ls.loadingtxt.setText("Database Tersambung !!");
                }
                if (i==75) {
                    ls.loadingtxt.setText("Memulai Aplikasi...");
                }
                ls.loadingBar.setValue(i);
                if(i==100){
                    ls.setVisible(false);
                    lgn.setVisible(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingtxt;
    private javax.swing.JLabel persentxt;
    // End of variables declaration//GEN-END:variables
}
