/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuAdmin;

import Login.menu_user;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class data_user extends javax.swing.JFrame {
    
    private void tampilankosong(){
        txnama.setText(null);
        txemail.setText(null);
        txpassword.setText(null);
        txgender.setText(null);
        txalamat.setText(null);
        txnotelp.setText(null);   
    }

    /**
     * Creates new form data_user
     */
    public data_user() {
        initComponents();
        btCari.setVisible(false);
        tampilantabeluser();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txpassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txalamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txgender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txnotelp = new javax.swing.JTextField();
        masukkannotelp = new javax.swing.JLabel();
        tfNoTelp = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "           Nama", "           Email", "          Password", "       Jenis Kelamin", "          Alamat", "        No. Telp"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 150, 1020, 180);

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 46, 66));
        jLabel6.setText("No. Telp:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 470, 130, 30);

        txemail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txemailActionPerformed(evt);
            }
        });
        getContentPane().add(txemail);
        txemail.setBounds(290, 420, 240, 40);

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 46, 66));
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 370, 120, 30);

        txnama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txnama);
        txnama.setBounds(290, 370, 240, 40);

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 46, 66));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 470, 150, 40);

        txpassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txpassword);
        txpassword.setBounds(290, 470, 240, 40);

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 46, 66));
        jLabel5.setText("Alamat:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 420, 110, 30);

        txalamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txalamat);
        txalamat.setBounds(750, 420, 240, 40);

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 46, 66));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 420, 100, 40);

        txgender.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txgenderActionPerformed(evt);
            }
        });
        getContentPane().add(txgender);
        txgender.setBounds(750, 370, 240, 40);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 46, 66));
        jLabel1.setText("Nama:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 370, 100, 40);

        txnotelp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnotelpActionPerformed(evt);
            }
        });
        getContentPane().add(txnotelp);
        txnotelp.setBounds(750, 470, 240, 40);

        masukkannotelp.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        masukkannotelp.setForeground(new java.awt.Color(29, 46, 66));
        masukkannotelp.setText("Cari/Edit (No. Telp):");
        masukkannotelp.setToolTipText("");
        getContentPane().add(masukkannotelp);
        masukkannotelp.setBounds(60, 560, 280, 40);

        tfNoTelp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tfNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTelpActionPerformed(evt);
            }
        });
        tfNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelpKeyTyped(evt);
            }
        });
        getContentPane().add(tfNoTelp);
        tfNoTelp.setBounds(320, 560, 310, 40);

        btCari.setBackground(new java.awt.Color(84, 173, 186));
        btCari.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btCari.setForeground(new java.awt.Color(29, 46, 66));
        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });
        getContentPane().add(btCari);
        btCari.setBounds(50, 620, 190, 48);

        btHapus.setBackground(new java.awt.Color(84, 173, 186));
        btHapus.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btHapus.setForeground(new java.awt.Color(29, 46, 66));
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btHapus);
        btHapus.setBounds(260, 620, 210, 50);

        btEdit.setBackground(new java.awt.Color(84, 173, 186));
        btEdit.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btEdit.setForeground(new java.awt.Color(29, 46, 66));
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit);
        btEdit.setBounds(490, 620, 203, 50);

        btKembali.setBackground(new java.awt.Color(84, 173, 186));
        btKembali.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btKembali.setForeground(new java.awt.Color(29, 46, 66));
        btKembali.setText("Kembali");
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btKembali);
        btKembali.setBounds(710, 620, 200, 51);

        btKeluar.setBackground(new java.awt.Color(84, 173, 186));
        btKeluar.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btKeluar.setForeground(new java.awt.Color(29, 46, 66));
        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar);
        btKeluar.setBounds(923, 620, 190, 51);

        title.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        title.setForeground(new java.awt.Color(29, 46, 66));
        title.setText("Data User");
        getContentPane().add(title);
        title.setBounds(430, 10, 270, 73);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/bg3.png"))); // NOI18N
        bg.setText("jLabel3");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1150, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void GetData(){
        try {
            Connection con = (Connection) Login.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql = stm.executeQuery("select * from tbregister");
            
        } catch (Exception e) {
        }
    }
    
    String telp = "";
    private void tampilantabeluser(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("                    Nama");
        tb.addColumn("                    Email");
        tb.addColumn("                 Password");
        tb.addColumn("              Jenis Kelamin");
        tb.addColumn("                    Alamat");
        tb.addColumn("                    No. Telp");

        jTable1.setModel(tb);
        
        try {
            Connection conn = (Connection) Login.koneksi.koneksiDB();
            Statement ppt =  conn.createStatement();
            ResultSet sql = ppt.executeQuery("select * from tbregister");
            
            while (sql.next()) {                
                GetData();
                tb.addRow(new Object[]{
                    sql.getString("nama"),
                    sql.getString("email"),
                    sql.getString("password"),
                    sql.getString("gender"),
                    sql.getString("alamat"),
                    sql.getString("notelp")
                });
            }
            
        } catch (Exception e) {
        }
        
    }
    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        
        telp = tfNoTelp.getText();
        try {
            Connection conn = (Connection) Login.koneksi.koneksiDB();
            Statement ppt =  conn.createStatement();
            ResultSet sql = ppt.executeQuery("select * from tbregister where notelp="+telp);
            
            if (sql.next()) {
                JOptionPane.showMessageDialog(this, 
                        "Nama: "+sql.getString("nama")+"\n"
                        +"Email: "+sql.getString("email")+"\n"
                        +"Password: "+sql.getString("password")+"\n"
                        +"Jenis Kelamin: "+sql.getString("gender")+"\n"
                        +"Alamat: "+sql.getString("alamat")+"\n"
                        +"No. Telp: "+sql.getString("notelp")+"\n","Data yang kami temukan...",1);
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btCariActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar?","Yakin?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
//        int i = jTable1.getSelectedRow();
//        if(i == -1){
//            return;
//        }
        
        try{
            String sql = "UPDATE tbregister SET nama='" + txnama.getText() 
                    + "',email='" + txemail.getText() 
                    + "',password='" + txpassword.getText()
                    + "',gender='" + txgender.getText() 
                    + "',alamat='" + txalamat.getText() 
                    + "',notelp='" + txnotelp.getText() 
                    + "' WHERE nama = '" + txnama.getText() + "'";
            java.sql.Connection conn = (Connection)Login.koneksi.koneksiDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil...");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilantabeluser();
        tampilankosong();
    }//GEN-LAST:event_btEditActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        // TODO add your handling code here:
        menu_admin menuadmin= new menu_admin ();
        menuadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKembaliActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
//        int i = jTable1.getSelectedRow();
//        if(i == -1){
//            return;
//        }
        
//        String id = (String)model.getValueAt(i, 0);
        
        try {
            String sql = "DELETE FROM tbregister WHERE nama='" + txnama.getText() + "'";
            java.sql.Connection conn = (Connection) Login.koneksi.koneksiDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil...");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilantabeluser();
        tampilankosong();
        
    }//GEN-LAST:event_btHapusActionPerformed

    private void tfNoTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelpKeyTyped
        // TODO add your handling code here:
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.addColumn("                    Nama");
        tb.addColumn("                    Email");
        tb.addColumn("                 Password");
        tb.addColumn("              Jenis Kelamin");
        tb.addColumn("                    Alamat");
        tb.addColumn("                    No. Telp");
                
        try{
            Connection conn = (Connection) Login.koneksi.koneksiDB();
            String sql = "Select * from tbregister where notelp like '%" + tfNoTelp.getText() + "%'";
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }
            jTable1.setModel(tb);
            GetData();
        }catch(Exception e){
           System.out.println("Cari Data Error");
        }finally{
        }
    }//GEN-LAST:event_tfNoTelpKeyTyped

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    private void txalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txalamatActionPerformed

    private void txnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnotelpActionPerformed

    private void txpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpasswordActionPerformed

    private void txemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txemailActionPerformed

    private void txgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txgenderActionPerformed

    private void tfNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTelpActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String nama = jTable1.getValueAt(baris, 0).toString();
        txnama.setText(nama);
        
        String email = jTable1.getValueAt(baris, 1).toString();
        txemail.setText(email);
        
        String password = jTable1.getValueAt(baris, 2).toString();
        txpassword.setText(password);
        
        String gender = jTable1.getValueAt(baris, 3).toString();
        txgender.setText(gender);
        
        String alamat = jTable1.getValueAt(baris, 4).toString();
        txalamat.setText(alamat);
        
        String telp = jTable1.getValueAt(baris, 5).toString();
        txnotelp.setText(telp);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btCari;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel masukkannotelp;
    private javax.swing.JTextField tfNoTelp;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txalamat;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txgender;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnotelp;
    private javax.swing.JTextField txpassword;
    // End of variables declaration//GEN-END:variables
}
