/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuAdmin;

import Login.menu_user;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form menu_admin
     */
    public menu_admin() {
        initComponents();
          this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btData = new javax.swing.JButton();
        btUang = new javax.swing.JButton();
        btBtb = new javax.swing.JButton();
        btBb = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setBackground(new java.awt.Color(29, 46, 66));
        title.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        title.setForeground(new java.awt.Color(29, 46, 66));
        title.setText("Menu Admin");
        getContentPane().add(title);
        title.setBounds(710, 70, 320, 61);

        btData.setBackground(new java.awt.Color(84, 173, 186));
        btData.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btData.setForeground(new java.awt.Color(29, 46, 66));
        btData.setText("Data User");
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });
        getContentPane().add(btData);
        btData.setBounds(770, 220, 190, 50);

        btUang.setBackground(new java.awt.Color(84, 173, 186));
        btUang.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btUang.setForeground(new java.awt.Color(29, 46, 66));
        btUang.setText("Wakaf Uang");
        btUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUangActionPerformed(evt);
            }
        });
        getContentPane().add(btUang);
        btUang.setBounds(760, 330, 220, 48);

        btBtb.setBackground(new java.awt.Color(84, 173, 186));
        btBtb.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btBtb.setForeground(new java.awt.Color(29, 46, 66));
        btBtb.setText("Wakaf Benda Tidak Bergerak");
        btBtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBtbActionPerformed(evt);
            }
        });
        getContentPane().add(btBtb);
        btBtb.setBounds(670, 440, 420, 51);

        btBb.setBackground(new java.awt.Color(84, 173, 186));
        btBb.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btBb.setForeground(new java.awt.Color(29, 46, 66));
        btBb.setText("Wakaf Benda Begerak");
        btBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBbActionPerformed(evt);
            }
        });
        getContentPane().add(btBb);
        btBb.setBounds(710, 550, 330, 51);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/3.png"))); // NOI18N
        getContentPane().add(image);
        image.setBounds(70, 220, 413, 279);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/bg1.png"))); // NOI18N
        bg.setText("jLabel4");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1150, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBtbActionPerformed
        // TODO add your handling code here:
       Wakaf_Benda_TidakBergerak WBTB= new Wakaf_Benda_TidakBergerak();
        WBTB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBtbActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataActionPerformed
        // TODO add your handling code here:
        data_user datauser= new data_user ();
        datauser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDataActionPerformed

    private void btUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUangActionPerformed
        // TODO add your handling code here:
        Wakaf_Uang WU= new Wakaf_Uang ();
        WU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btUangActionPerformed

    private void btBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBbActionPerformed
        // TODO add your handling code here:
        Wakaf_BendaBergerak WBB = new Wakaf_BendaBergerak();
        WBB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btBb;
    private javax.swing.JButton btBtb;
    private javax.swing.JButton btData;
    private javax.swing.JButton btUang;
    private javax.swing.JLabel image;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
