/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import MenuAdmin.LoginAdmin;
import MenuAdmin.menu_admin;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        jButton1.setVisible(false);
      this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void GetData(){
        try {
            Connection conn= (Connection) Login.koneksi.koneksiDB();
            Statement stm = conn.createStatement();
            ResultSet sql = stm.executeQuery("select * from tbregister");
            
        } catch (Exception e) {
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selamatdatang = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        desc4 = new javax.swing.JLabel();
        desc5 = new javax.swing.JLabel();
        desc6 = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        signin = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        cbApakah = new javax.swing.JCheckBox();
        btSignIn = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btSignUp1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        selamatdatang.setBackground(new java.awt.Color(29, 46, 66));
        selamatdatang.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        selamatdatang.setForeground(new java.awt.Color(29, 46, 66));
        selamatdatang.setText("Selamat Datang");
        getContentPane().add(selamatdatang);
        selamatdatang.setBounds(40, 70, 440, 61);

        desc1.setBackground(new java.awt.Color(29, 46, 66));
        desc1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc1.setForeground(new java.awt.Color(29, 46, 66));
        desc1.setText("ANJIM singkatan dari Amalan Jariah Itu");
        getContentPane().add(desc1);
        desc1.setBounds(40, 160, 663, 51);

        desc2.setBackground(new java.awt.Color(29, 46, 66));
        desc2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc2.setForeground(new java.awt.Color(29, 46, 66));
        desc2.setText("Mulia merupakan salah satu aplikasi   ");
        getContentPane().add(desc2);
        desc2.setBounds(40, 210, 561, 51);

        desc3.setBackground(new java.awt.Color(29, 46, 66));
        desc3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc3.setForeground(new java.awt.Color(29, 46, 66));
        desc3.setText("wakaf berbasis digital.");
        getContentPane().add(desc3);
        desc3.setBounds(40, 260, 510, 50);

        desc4.setBackground(new java.awt.Color(29, 46, 66));
        desc4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc4.setForeground(new java.awt.Color(29, 46, 66));
        desc4.setText("Aplikasi ini dibuat untuk mempermudah");
        getContentPane().add(desc4);
        desc4.setBounds(40, 370, 550, 32);

        desc5.setBackground(new java.awt.Color(29, 46, 66));
        desc5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc5.setForeground(new java.awt.Color(29, 46, 66));
        desc5.setText("masyarakat untuk membayar waqaf");
        getContentPane().add(desc5);
        desc5.setBounds(40, 410, 490, 40);

        desc6.setBackground(new java.awt.Color(29, 46, 66));
        desc6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        desc6.setForeground(new java.awt.Color(29, 46, 66));
        desc6.setText("lewat gadget pribadinya");
        getContentPane().add(desc6);
        desc6.setBounds(40, 450, 340, 50);

        Admin.setBackground(new java.awt.Color(84, 173, 186));
        Admin.setFont(new java.awt.Font("Montserrat", 1, 27)); // NOI18N
        Admin.setForeground(new java.awt.Color(29, 46, 66));
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin);
        Admin.setBounds(306, 561, 153, 51);

        signin.setBackground(new java.awt.Color(29, 46, 66));
        signin.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        signin.setForeground(new java.awt.Color(29, 46, 66));
        signin.setText("Sign In");
        getContentPane().add(signin);
        signin.setBounds(810, 70, 181, 61);

        email.setBackground(new java.awt.Color(29, 46, 66));
        email.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(29, 46, 66));
        email.setText("Email");
        getContentPane().add(email);
        email.setBounds(710, 170, 102, 51);

        password.setBackground(new java.awt.Color(29, 46, 66));
        password.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(29, 46, 66));
        password.setText("Password");
        getContentPane().add(password);
        password.setBounds(710, 280, 150, 51);

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(710, 230, 380, 51);

        cbApakah.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        cbApakah.setForeground(new java.awt.Color(29, 46, 66));
        cbApakah.setText("Apakah anda sudah yakin?");
        cbApakah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbApakahActionPerformed(evt);
            }
        });
        getContentPane().add(cbApakah);
        cbApakah.setBounds(710, 380, 320, 51);

        btSignIn.setBackground(new java.awt.Color(84, 173, 186));
        btSignIn.setFont(new java.awt.Font("Montserrat", 1, 27)); // NOI18N
        btSignIn.setForeground(new java.awt.Color(29, 46, 66));
        btSignIn.setText("Sign In");
        btSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btSignIn);
        btSignIn.setBounds(790, 550, 153, 51);

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(710, 330, 380, 51);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1141, 690, 10, 10);

        btSignUp1.setBackground(new java.awt.Color(84, 173, 186));
        btSignUp1.setFont(new java.awt.Font("Montserrat", 1, 27)); // NOI18N
        btSignUp1.setForeground(new java.awt.Color(29, 46, 66));
        btSignUp1.setText("Sign Up");
        btSignUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSignUp1);
        btSignUp1.setBounds(102, 561, 153, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/bg1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1173, 714);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbApakahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbApakahActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(true);
    }//GEN-LAST:event_cbApakahActionPerformed

    private void btSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignInActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection conn = (Connection) Login.koneksi.koneksiDB();
            Statement s = conn.createStatement();
            
            String sql = "SELECT * FROM tbregister WHERE email='" + tfEmail.getText()
                    +"' and password='"+ tfPassword.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                menu_user menuuser= new menu_user ();
                menuuser.setVisible(true);
                this.dispose(); //close the form
            
            }else{
                JOptionPane.showMessageDialog(null, "Email atau Password Salah");
                tfPassword.requestFocus();
                
            }
        }catch(SQLException e){
            System.out.println("error");
        }
    }

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar?","Yakin?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btSignInActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        LoginAdmin admin = new LoginAdmin ();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuAdmin.menu_admin masuk = new menu_admin();
        masuk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btSignUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUp1ActionPerformed
        // TODO add your handling code here:
        register regis = new register();
        regis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSignUp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton btSignIn;
    private javax.swing.JButton btSignUp1;
    private javax.swing.JCheckBox cbApakah;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JLabel desc4;
    private javax.swing.JLabel desc5;
    private javax.swing.JLabel desc6;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel selamatdatang;
    private javax.swing.JLabel signin;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
