/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class menu_user extends javax.swing.JFrame {

    /**
     * Creates new form menu_user
     */
    public menu_user() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        uang1 = new javax.swing.JLabel();
        uang2 = new javax.swing.JLabel();
        btb1 = new javax.swing.JLabel();
        btb2 = new javax.swing.JLabel();
        btb3 = new javax.swing.JLabel();
        btb4 = new javax.swing.JLabel();
        btb5 = new javax.swing.JLabel();
        bb1 = new javax.swing.JLabel();
        bb2 = new javax.swing.JLabel();
        bb3 = new javax.swing.JLabel();
        bb4 = new javax.swing.JLabel();
        bb5 = new javax.swing.JLabel();
        bb6 = new javax.swing.JLabel();
        bb7 = new javax.swing.JLabel();
        bb8 = new javax.swing.JLabel();
        bb9 = new javax.swing.JLabel();
        btUang = new javax.swing.JButton();
        btBtb = new javax.swing.JButton();
        btBb = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setBackground(new java.awt.Color(29, 46, 66));
        title.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        title.setForeground(new java.awt.Color(29, 46, 66));
        title.setText("Silahkan Pilih Jenis Wakaf Anda");
        getContentPane().add(title);
        title.setBounds(200, 0, 809, 102);

        uang1.setBackground(new java.awt.Color(29, 46, 66));
        uang1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        uang1.setForeground(new java.awt.Color(29, 46, 66));
        uang1.setText("Wakaf Uang");
        getContentPane().add(uang1);
        uang1.setBounds(330, 110, 204, 37);

        uang2.setBackground(new java.awt.Color(29, 46, 66));
        uang2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        uang2.setForeground(new java.awt.Color(29, 46, 66));
        uang2.setText("-(Wakaf tunai,cash,wakaf)");
        getContentPane().add(uang2);
        uang2.setBounds(330, 150, 380, 30);

        btb1.setBackground(new java.awt.Color(29, 46, 66));
        btb1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btb1.setForeground(new java.awt.Color(29, 46, 66));
        btb1.setText("Wakaf Benda Tidak Bergerak");
        getContentPane().add(btb1);
        btb1.setBounds(330, 190, 438, 37);

        btb2.setBackground(new java.awt.Color(29, 46, 66));
        btb2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btb2.setForeground(new java.awt.Color(29, 46, 66));
        btb2.setText("-Hak atas tanah : hak milik, strata title, HGB/HGU/HP");
        getContentPane().add(btb2);
        btb2.setBounds(330, 230, 690, 30);

        btb3.setBackground(new java.awt.Color(29, 46, 66));
        btb3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btb3.setForeground(new java.awt.Color(29, 46, 66));
        btb3.setText("-Bangunan atau bagian bangunan atau satuan rumah susun");
        getContentPane().add(btb3);
        btb3.setBounds(330, 260, 800, 27);

        btb4.setBackground(new java.awt.Color(29, 46, 66));
        btb4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btb4.setForeground(new java.awt.Color(29, 46, 66));
        btb4.setText("-Tanaman dan benda lain yang berkaitan dengan tanah");
        getContentPane().add(btb4);
        btb4.setBounds(330, 290, 740, 30);

        btb5.setBackground(new java.awt.Color(29, 46, 66));
        btb5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btb5.setForeground(new java.awt.Color(29, 46, 66));
        btb5.setText("-Benda tidak bergerak lain");
        getContentPane().add(btb5);
        btb5.setBounds(330, 320, 380, 30);

        bb1.setBackground(new java.awt.Color(29, 46, 66));
        bb1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        bb1.setForeground(new java.awt.Color(29, 46, 66));
        bb1.setText("Wakaf Benda Bergerak");
        getContentPane().add(bb1);
        bb1.setBounds(330, 360, 347, 37);

        bb2.setBackground(new java.awt.Color(29, 46, 66));
        bb2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb2.setForeground(new java.awt.Color(29, 46, 66));
        bb2.setText("-Benda dapat berpindah");
        getContentPane().add(bb2);
        bb2.setBounds(330, 400, 320, 30);

        bb3.setBackground(new java.awt.Color(29, 46, 66));
        bb3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb3.setForeground(new java.awt.Color(29, 46, 66));
        bb3.setText("-Benda dapat dihabiskan dan tidak dapat dihabiskan");
        getContentPane().add(bb3);
        bb3.setBounds(330, 430, 700, 30);

        bb4.setBackground(new java.awt.Color(29, 46, 66));
        bb4.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb4.setForeground(new java.awt.Color(29, 46, 66));
        bb4.setText("-Air dan BBM");
        getContentPane().add(bb4);
        bb4.setBounds(330, 460, 180, 30);

        bb5.setBackground(new java.awt.Color(29, 46, 66));
        bb5.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb5.setForeground(new java.awt.Color(29, 46, 66));
        bb5.setText("-Benda bergerak karena sifatnya yang dapat diwakafkan");
        getContentPane().add(bb5);
        bb5.setBounds(330, 490, 729, 30);

        bb6.setBackground(new java.awt.Color(29, 46, 66));
        bb6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb6.setForeground(new java.awt.Color(29, 46, 66));
        bb6.setText("-Benda bergerak selain uang");
        getContentPane().add(bb6);
        bb6.setBounds(330, 520, 380, 30);

        bb7.setBackground(new java.awt.Color(29, 46, 66));
        bb7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb7.setForeground(new java.awt.Color(29, 46, 66));
        bb7.setText("-Surat berharga");
        getContentPane().add(bb7);
        bb7.setBounds(330, 540, 230, 40);

        bb8.setBackground(new java.awt.Color(29, 46, 66));
        bb8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb8.setForeground(new java.awt.Color(29, 46, 66));
        bb8.setText("-Hak Atas Kekayaan Intelektual");
        getContentPane().add(bb8);
        bb8.setBounds(330, 570, 440, 30);

        bb9.setBackground(new java.awt.Color(29, 46, 66));
        bb9.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        bb9.setForeground(new java.awt.Color(29, 46, 66));
        bb9.setText("-Hak atas benda bergerak lainnya");
        getContentPane().add(bb9);
        bb9.setBounds(330, 600, 440, 30);

        btUang.setBackground(new java.awt.Color(84, 173, 186));
        btUang.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btUang.setForeground(new java.awt.Color(29, 46, 66));
        btUang.setText("Uang");
        btUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUangActionPerformed(evt);
            }
        });
        getContentPane().add(btUang);
        btUang.setBounds(340, 640, 160, 51);

        btBtb.setBackground(new java.awt.Color(84, 173, 186));
        btBtb.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btBtb.setForeground(new java.awt.Color(29, 46, 66));
        btBtb.setText("Benda Tidak Bergerak");
        btBtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBtbActionPerformed(evt);
            }
        });
        getContentPane().add(btBtb);
        btBtb.setBounds(510, 640, 330, 51);

        btBb.setBackground(new java.awt.Color(84, 173, 186));
        btBb.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        btBb.setForeground(new java.awt.Color(29, 46, 66));
        btBb.setText("Benda Bergerak");
        btBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBbActionPerformed(evt);
            }
        });
        getContentPane().add(btBb);
        btBb.setBounds(846, 640, 270, 51);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/2.png"))); // NOI18N
        getContentPane().add(image);
        image.setBounds(50, 120, 280, 500);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/bg3.png"))); // NOI18N
        bg.setText("jLabel20");
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1150, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUangActionPerformed
        // TODO add your handling code here:
        wakaf_uang wakafuang= new wakaf_uang ();
        wakafuang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btUangActionPerformed

    private void btBtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBtbActionPerformed
        // TODO add your handling code here:
        wakaf_benda_tidak_bergerak bendatidakbergerak = new wakaf_benda_tidak_bergerak ();
        bendatidakbergerak.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBtbActionPerformed

    private void btBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBbActionPerformed
        // TODO add your handling code here:
        wakaf_benda_bergerak bendabergerak = new wakaf_benda_bergerak ();
        bendabergerak.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bb1;
    private javax.swing.JLabel bb2;
    private javax.swing.JLabel bb3;
    private javax.swing.JLabel bb4;
    private javax.swing.JLabel bb5;
    private javax.swing.JLabel bb6;
    private javax.swing.JLabel bb7;
    private javax.swing.JLabel bb8;
    private javax.swing.JLabel bb9;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btBb;
    private javax.swing.JButton btBtb;
    private javax.swing.JButton btUang;
    private javax.swing.JLabel btb1;
    private javax.swing.JLabel btb2;
    private javax.swing.JLabel btb3;
    private javax.swing.JLabel btb4;
    private javax.swing.JLabel btb5;
    private javax.swing.JLabel image;
    private javax.swing.JLabel title;
    private javax.swing.JLabel uang1;
    private javax.swing.JLabel uang2;
    // End of variables declaration//GEN-END:variables
}
